/********************************************************************************
** Form generated from reading UI file 'ScenarioGenerationDialog.ui'
**
** Created by: Qt User Interface Compiler version 5.8.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SCENARIOGENERATIONDIALOG_H
#define UI_SCENARIOGENERATIONDIALOG_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_ScenarioGenerationDialog
{
public:
    QPushButton *pushButtonOK;
    QPushButton *pushButtonCancel;
    QLabel *label;
    QLineEdit *lineEditNumScenarios;
    QLabel *label_2;
    QLineEdit *lineEditOutputDirectory;
    QPushButton *pushButtonOutputDirectory;
    QLabel *label_13;
    QLabel *label_14;
    QLineEdit *lineEditZone;
    QLineEdit *lineEditTerrain;
    QPushButton *pushButtonZone;
    QPushButton *pushButtonTerrain;
    QGroupBox *groupBox;
    QLabel *label_9;
    QLineEdit *lineEditAvenueSegmentLengthMin;
    QLineEdit *lineEditRoadCurvatureMin;
    QLineEdit *lineEditRoadBaseOrientationMax;
    QLabel *label_6;
    QLineEdit *lineEditRoadCurvatureMax;
    QLabel *label_3;
    QLineEdit *lineEditAvenueSegmentLengthMax;
    QLineEdit *lineEditRoadBaseOrientationMin;
    QLabel *label_4;
    QLabel *label_7;
    QLabel *label_10;
    QLabel *label_5;
    QLabel *label_8;
    QLabel *label_29;
    QLineEdit *lineEditMajorRoadWidthMin;
    QLineEdit *lineEditMajorRoadWidthMax;
    QLabel *label_30;
    QLabel *label_31;
    QLineEdit *lineEditMinorRoadWidthMax;
    QLabel *label_32;
    QLabel *label_35;
    QLineEdit *lineEditMinorRoadWidthMin;
    QLabel *label_39;
    QLabel *label_42;
    QCheckBox *checkBoxUseElevation;
    QGroupBox *groupBox_2;
    QLabel *label_11;
    QLineEdit *lineEditParkRatioMin;
    QLineEdit *lineEditParkRatioMax;
    QLabel *label_12;
    QLabel *label_15;
    QLineEdit *lineEditParcelAreaMin;
    QLineEdit *lineEditParcelAreaMax;
    QLabel *label_16;
    QLabel *label_17;
    QLineEdit *lineEditSetbackFrontMin;
    QLineEdit *lineEditSetbackFrontMax;
    QLabel *label_18;
    QLabel *label_19;
    QLineEdit *lineEditSetbackRearMin;
    QLineEdit *lineEditSetbackRearMax;
    QLabel *label_20;
    QLabel *label_21;
    QLineEdit *lineEditSetbackSideMin;
    QLineEdit *lineEditSetbackSideMax;
    QLabel *label_22;
    QLabel *label_38;
    QLineEdit *lineEditParcelAreaDev;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QGroupBox *groupBox_3;
    QLabel *label_33;
    QLineEdit *lineEditNumStoriesMin;
    QLineEdit *lineEditNumStoriesMax;
    QLabel *label_34;
    QLabel *label_36;
    QLineEdit *lineEditMinBuildingDimMin;
    QLineEdit *lineEditMinBuildingDimMax;
    QLabel *label_37;
    QLabel *label_27;
    QLabel *label_43;
    QCheckBox *checkBoxBuildingCoverage;
    QLineEdit *lineEditBuildingCoverageMin;
    QLineEdit *lineEditBuildingCoverageMax;
    QLabel *label_44;
    QLabel *label_45;
    QLineEdit *lineEditSimulatorDirectory;
    QLabel *label_28;
    QPushButton *pushButtonSimulatorDirectory;
    QCheckBox *checkBoxUseSimulator;
    QLabel *label_40;
    QCheckBox *checkBoxGenerateBuildingFootprintsImage;
    QLabel *label_41;
    QLineEdit *lineEditBuildingFootprintsImageSize;

    void setupUi(QDialog *ScenarioGenerationDialog)
    {
        if (ScenarioGenerationDialog->objectName().isEmpty())
            ScenarioGenerationDialog->setObjectName(QStringLiteral("ScenarioGenerationDialog"));
        ScenarioGenerationDialog->resize(544, 774);
        pushButtonOK = new QPushButton(ScenarioGenerationDialog);
        pushButtonOK->setObjectName(QStringLiteral("pushButtonOK"));
        pushButtonOK->setGeometry(QRect(330, 730, 91, 31));
        pushButtonCancel = new QPushButton(ScenarioGenerationDialog);
        pushButtonCancel->setObjectName(QStringLiteral("pushButtonCancel"));
        pushButtonCancel->setGeometry(QRect(440, 730, 91, 31));
        label = new QLabel(ScenarioGenerationDialog);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(20, 70, 61, 21));
        lineEditNumScenarios = new QLineEdit(ScenarioGenerationDialog);
        lineEditNumScenarios->setObjectName(QStringLiteral("lineEditNumScenarios"));
        lineEditNumScenarios->setGeometry(QRect(130, 70, 71, 20));
        label_2 = new QLabel(ScenarioGenerationDialog);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(20, 100, 91, 21));
        lineEditOutputDirectory = new QLineEdit(ScenarioGenerationDialog);
        lineEditOutputDirectory->setObjectName(QStringLiteral("lineEditOutputDirectory"));
        lineEditOutputDirectory->setGeometry(QRect(130, 100, 361, 20));
        pushButtonOutputDirectory = new QPushButton(ScenarioGenerationDialog);
        pushButtonOutputDirectory->setObjectName(QStringLiteral("pushButtonOutputDirectory"));
        pushButtonOutputDirectory->setGeometry(QRect(500, 100, 31, 23));
        label_13 = new QLabel(ScenarioGenerationDialog);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(20, 10, 91, 21));
        label_14 = new QLabel(ScenarioGenerationDialog);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(20, 40, 91, 21));
        lineEditZone = new QLineEdit(ScenarioGenerationDialog);
        lineEditZone->setObjectName(QStringLiteral("lineEditZone"));
        lineEditZone->setGeometry(QRect(130, 10, 361, 20));
        lineEditTerrain = new QLineEdit(ScenarioGenerationDialog);
        lineEditTerrain->setObjectName(QStringLiteral("lineEditTerrain"));
        lineEditTerrain->setGeometry(QRect(130, 40, 361, 20));
        pushButtonZone = new QPushButton(ScenarioGenerationDialog);
        pushButtonZone->setObjectName(QStringLiteral("pushButtonZone"));
        pushButtonZone->setGeometry(QRect(500, 10, 31, 23));
        pushButtonTerrain = new QPushButton(ScenarioGenerationDialog);
        pushButtonTerrain->setObjectName(QStringLiteral("pushButtonTerrain"));
        pushButtonTerrain->setGeometry(QRect(500, 40, 31, 23));
        groupBox = new QGroupBox(ScenarioGenerationDialog);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(10, 180, 521, 201));
        label_9 = new QLabel(groupBox);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(20, 80, 121, 21));
        lineEditAvenueSegmentLengthMin = new QLineEdit(groupBox);
        lineEditAvenueSegmentLengthMin->setObjectName(QStringLiteral("lineEditAvenueSegmentLengthMin"));
        lineEditAvenueSegmentLengthMin->setGeometry(QRect(150, 20, 71, 20));
        lineEditRoadCurvatureMin = new QLineEdit(groupBox);
        lineEditRoadCurvatureMin->setObjectName(QStringLiteral("lineEditRoadCurvatureMin"));
        lineEditRoadCurvatureMin->setGeometry(QRect(150, 80, 71, 20));
        lineEditRoadBaseOrientationMax = new QLineEdit(groupBox);
        lineEditRoadBaseOrientationMax->setObjectName(QStringLiteral("lineEditRoadBaseOrientationMax"));
        lineEditRoadBaseOrientationMax->setGeometry(QRect(240, 50, 71, 20));
        label_6 = new QLabel(groupBox);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(20, 50, 121, 21));
        lineEditRoadCurvatureMax = new QLineEdit(groupBox);
        lineEditRoadCurvatureMax->setObjectName(QStringLiteral("lineEditRoadCurvatureMax"));
        lineEditRoadCurvatureMax->setGeometry(QRect(240, 80, 71, 20));
        label_3 = new QLabel(groupBox);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(20, 20, 121, 21));
        lineEditAvenueSegmentLengthMax = new QLineEdit(groupBox);
        lineEditAvenueSegmentLengthMax->setObjectName(QStringLiteral("lineEditAvenueSegmentLengthMax"));
        lineEditAvenueSegmentLengthMax->setGeometry(QRect(240, 20, 71, 20));
        lineEditRoadBaseOrientationMin = new QLineEdit(groupBox);
        lineEditRoadBaseOrientationMin->setObjectName(QStringLiteral("lineEditRoadBaseOrientationMin"));
        lineEditRoadBaseOrientationMin->setGeometry(QRect(150, 50, 71, 20));
        label_4 = new QLabel(groupBox);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(226, 20, 16, 21));
        label_7 = new QLabel(groupBox);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(226, 50, 16, 21));
        label_10 = new QLabel(groupBox);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(226, 80, 16, 21));
        label_5 = new QLabel(groupBox);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(320, 20, 16, 21));
        label_8 = new QLabel(groupBox);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(320, 50, 31, 21));
        label_29 = new QLabel(groupBox);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(20, 110, 121, 21));
        lineEditMajorRoadWidthMin = new QLineEdit(groupBox);
        lineEditMajorRoadWidthMin->setObjectName(QStringLiteral("lineEditMajorRoadWidthMin"));
        lineEditMajorRoadWidthMin->setGeometry(QRect(150, 110, 71, 20));
        lineEditMajorRoadWidthMax = new QLineEdit(groupBox);
        lineEditMajorRoadWidthMax->setObjectName(QStringLiteral("lineEditMajorRoadWidthMax"));
        lineEditMajorRoadWidthMax->setGeometry(QRect(240, 110, 71, 20));
        label_30 = new QLabel(groupBox);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(320, 110, 16, 21));
        label_31 = new QLabel(groupBox);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(226, 110, 16, 21));
        lineEditMinorRoadWidthMax = new QLineEdit(groupBox);
        lineEditMinorRoadWidthMax->setObjectName(QStringLiteral("lineEditMinorRoadWidthMax"));
        lineEditMinorRoadWidthMax->setGeometry(QRect(240, 140, 71, 20));
        label_32 = new QLabel(groupBox);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(20, 140, 121, 21));
        label_35 = new QLabel(groupBox);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(320, 140, 16, 21));
        lineEditMinorRoadWidthMin = new QLineEdit(groupBox);
        lineEditMinorRoadWidthMin->setObjectName(QStringLiteral("lineEditMinorRoadWidthMin"));
        lineEditMinorRoadWidthMin->setGeometry(QRect(150, 140, 71, 20));
        label_39 = new QLabel(groupBox);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(226, 140, 16, 21));
        label_42 = new QLabel(groupBox);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(20, 170, 121, 21));
        checkBoxUseElevation = new QCheckBox(groupBox);
        checkBoxUseElevation->setObjectName(QStringLiteral("checkBoxUseElevation"));
        checkBoxUseElevation->setGeometry(QRect(150, 170, 70, 21));
        groupBox_2 = new QGroupBox(ScenarioGenerationDialog);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(10, 390, 521, 171));
        label_11 = new QLabel(groupBox_2);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(20, 20, 121, 21));
        lineEditParkRatioMin = new QLineEdit(groupBox_2);
        lineEditParkRatioMin->setObjectName(QStringLiteral("lineEditParkRatioMin"));
        lineEditParkRatioMin->setGeometry(QRect(150, 20, 71, 20));
        lineEditParkRatioMax = new QLineEdit(groupBox_2);
        lineEditParkRatioMax->setObjectName(QStringLiteral("lineEditParkRatioMax"));
        lineEditParkRatioMax->setGeometry(QRect(240, 20, 71, 20));
        label_12 = new QLabel(groupBox_2);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(226, 20, 16, 21));
        label_15 = new QLabel(groupBox_2);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(20, 50, 121, 21));
        lineEditParcelAreaMin = new QLineEdit(groupBox_2);
        lineEditParcelAreaMin->setObjectName(QStringLiteral("lineEditParcelAreaMin"));
        lineEditParcelAreaMin->setGeometry(QRect(150, 50, 71, 20));
        lineEditParcelAreaMax = new QLineEdit(groupBox_2);
        lineEditParcelAreaMax->setObjectName(QStringLiteral("lineEditParcelAreaMax"));
        lineEditParcelAreaMax->setGeometry(QRect(240, 50, 71, 20));
        label_16 = new QLabel(groupBox_2);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(226, 50, 16, 21));
        label_17 = new QLabel(groupBox_2);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(20, 80, 121, 21));
        lineEditSetbackFrontMin = new QLineEdit(groupBox_2);
        lineEditSetbackFrontMin->setObjectName(QStringLiteral("lineEditSetbackFrontMin"));
        lineEditSetbackFrontMin->setGeometry(QRect(150, 80, 71, 20));
        lineEditSetbackFrontMax = new QLineEdit(groupBox_2);
        lineEditSetbackFrontMax->setObjectName(QStringLiteral("lineEditSetbackFrontMax"));
        lineEditSetbackFrontMax->setGeometry(QRect(240, 80, 71, 20));
        label_18 = new QLabel(groupBox_2);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(226, 80, 16, 21));
        label_19 = new QLabel(groupBox_2);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(20, 110, 121, 21));
        lineEditSetbackRearMin = new QLineEdit(groupBox_2);
        lineEditSetbackRearMin->setObjectName(QStringLiteral("lineEditSetbackRearMin"));
        lineEditSetbackRearMin->setGeometry(QRect(150, 110, 71, 20));
        lineEditSetbackRearMax = new QLineEdit(groupBox_2);
        lineEditSetbackRearMax->setObjectName(QStringLiteral("lineEditSetbackRearMax"));
        lineEditSetbackRearMax->setGeometry(QRect(240, 110, 71, 20));
        label_20 = new QLabel(groupBox_2);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(226, 110, 16, 21));
        label_21 = new QLabel(groupBox_2);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(20, 140, 121, 21));
        lineEditSetbackSideMin = new QLineEdit(groupBox_2);
        lineEditSetbackSideMin->setObjectName(QStringLiteral("lineEditSetbackSideMin"));
        lineEditSetbackSideMin->setGeometry(QRect(150, 140, 71, 20));
        lineEditSetbackSideMax = new QLineEdit(groupBox_2);
        lineEditSetbackSideMax->setObjectName(QStringLiteral("lineEditSetbackSideMax"));
        lineEditSetbackSideMax->setGeometry(QRect(240, 140, 71, 20));
        label_22 = new QLabel(groupBox_2);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(226, 140, 16, 21));
        label_38 = new QLabel(groupBox_2);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(370, 50, 51, 21));
        lineEditParcelAreaDev = new QLineEdit(groupBox_2);
        lineEditParcelAreaDev->setObjectName(QStringLiteral("lineEditParcelAreaDev"));
        lineEditParcelAreaDev->setGeometry(QRect(430, 50, 71, 20));
        label_23 = new QLabel(groupBox_2);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(320, 80, 16, 21));
        label_24 = new QLabel(groupBox_2);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(320, 110, 16, 21));
        label_25 = new QLabel(groupBox_2);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(320, 140, 16, 21));
        label_26 = new QLabel(groupBox_2);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(320, 50, 31, 21));
        groupBox_3 = new QGroupBox(ScenarioGenerationDialog);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(10, 570, 521, 111));
        label_33 = new QLabel(groupBox_3);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(20, 20, 121, 21));
        lineEditNumStoriesMin = new QLineEdit(groupBox_3);
        lineEditNumStoriesMin->setObjectName(QStringLiteral("lineEditNumStoriesMin"));
        lineEditNumStoriesMin->setGeometry(QRect(150, 20, 71, 20));
        lineEditNumStoriesMax = new QLineEdit(groupBox_3);
        lineEditNumStoriesMax->setObjectName(QStringLiteral("lineEditNumStoriesMax"));
        lineEditNumStoriesMax->setGeometry(QRect(240, 20, 71, 20));
        label_34 = new QLabel(groupBox_3);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(226, 20, 16, 21));
        label_36 = new QLabel(groupBox_3);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(20, 50, 121, 21));
        lineEditMinBuildingDimMin = new QLineEdit(groupBox_3);
        lineEditMinBuildingDimMin->setObjectName(QStringLiteral("lineEditMinBuildingDimMin"));
        lineEditMinBuildingDimMin->setGeometry(QRect(150, 50, 71, 20));
        lineEditMinBuildingDimMax = new QLineEdit(groupBox_3);
        lineEditMinBuildingDimMax->setObjectName(QStringLiteral("lineEditMinBuildingDimMax"));
        lineEditMinBuildingDimMax->setGeometry(QRect(240, 50, 71, 20));
        label_37 = new QLabel(groupBox_3);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(226, 50, 16, 21));
        label_27 = new QLabel(groupBox_3);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(320, 50, 16, 21));
        label_43 = new QLabel(groupBox_3);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(20, 80, 121, 21));
        checkBoxBuildingCoverage = new QCheckBox(groupBox_3);
        checkBoxBuildingCoverage->setObjectName(QStringLiteral("checkBoxBuildingCoverage"));
        checkBoxBuildingCoverage->setGeometry(QRect(150, 80, 21, 21));
        lineEditBuildingCoverageMin = new QLineEdit(groupBox_3);
        lineEditBuildingCoverageMin->setObjectName(QStringLiteral("lineEditBuildingCoverageMin"));
        lineEditBuildingCoverageMin->setGeometry(QRect(200, 80, 71, 20));
        lineEditBuildingCoverageMax = new QLineEdit(groupBox_3);
        lineEditBuildingCoverageMax->setObjectName(QStringLiteral("lineEditBuildingCoverageMax"));
        lineEditBuildingCoverageMax->setGeometry(QRect(290, 80, 71, 20));
        label_44 = new QLabel(groupBox_3);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(275, 80, 16, 21));
        label_45 = new QLabel(groupBox_3);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(370, 80, 21, 21));
        lineEditSimulatorDirectory = new QLineEdit(ScenarioGenerationDialog);
        lineEditSimulatorDirectory->setObjectName(QStringLiteral("lineEditSimulatorDirectory"));
        lineEditSimulatorDirectory->setGeometry(QRect(130, 150, 361, 20));
        label_28 = new QLabel(ScenarioGenerationDialog);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(20, 150, 101, 21));
        pushButtonSimulatorDirectory = new QPushButton(ScenarioGenerationDialog);
        pushButtonSimulatorDirectory->setObjectName(QStringLiteral("pushButtonSimulatorDirectory"));
        pushButtonSimulatorDirectory->setGeometry(QRect(500, 150, 31, 23));
        checkBoxUseSimulator = new QCheckBox(ScenarioGenerationDialog);
        checkBoxUseSimulator->setObjectName(QStringLiteral("checkBoxUseSimulator"));
        checkBoxUseSimulator->setGeometry(QRect(20, 130, 101, 17));
        label_40 = new QLabel(ScenarioGenerationDialog);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(20, 690, 181, 21));
        checkBoxGenerateBuildingFootprintsImage = new QCheckBox(ScenarioGenerationDialog);
        checkBoxGenerateBuildingFootprintsImage->setObjectName(QStringLiteral("checkBoxGenerateBuildingFootprintsImage"));
        checkBoxGenerateBuildingFootprintsImage->setGeometry(QRect(210, 690, 70, 21));
        label_41 = new QLabel(ScenarioGenerationDialog);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(280, 690, 61, 21));
        lineEditBuildingFootprintsImageSize = new QLineEdit(ScenarioGenerationDialog);
        lineEditBuildingFootprintsImageSize->setObjectName(QStringLiteral("lineEditBuildingFootprintsImageSize"));
        lineEditBuildingFootprintsImageSize->setGeometry(QRect(340, 690, 71, 20));
        QWidget::setTabOrder(lineEditZone, pushButtonZone);
        QWidget::setTabOrder(pushButtonZone, lineEditTerrain);
        QWidget::setTabOrder(lineEditTerrain, pushButtonTerrain);
        QWidget::setTabOrder(pushButtonTerrain, lineEditNumScenarios);
        QWidget::setTabOrder(lineEditNumScenarios, lineEditOutputDirectory);
        QWidget::setTabOrder(lineEditOutputDirectory, pushButtonOutputDirectory);
        QWidget::setTabOrder(pushButtonOutputDirectory, checkBoxUseSimulator);
        QWidget::setTabOrder(checkBoxUseSimulator, lineEditSimulatorDirectory);
        QWidget::setTabOrder(lineEditSimulatorDirectory, pushButtonSimulatorDirectory);
        QWidget::setTabOrder(pushButtonSimulatorDirectory, lineEditAvenueSegmentLengthMin);
        QWidget::setTabOrder(lineEditAvenueSegmentLengthMin, lineEditAvenueSegmentLengthMax);
        QWidget::setTabOrder(lineEditAvenueSegmentLengthMax, lineEditRoadBaseOrientationMin);
        QWidget::setTabOrder(lineEditRoadBaseOrientationMin, lineEditRoadBaseOrientationMax);
        QWidget::setTabOrder(lineEditRoadBaseOrientationMax, lineEditRoadCurvatureMin);
        QWidget::setTabOrder(lineEditRoadCurvatureMin, lineEditRoadCurvatureMax);
        QWidget::setTabOrder(lineEditRoadCurvatureMax, lineEditMajorRoadWidthMin);
        QWidget::setTabOrder(lineEditMajorRoadWidthMin, lineEditMajorRoadWidthMax);
        QWidget::setTabOrder(lineEditMajorRoadWidthMax, lineEditParkRatioMin);
        QWidget::setTabOrder(lineEditParkRatioMin, lineEditParkRatioMax);
        QWidget::setTabOrder(lineEditParkRatioMax, lineEditParcelAreaMin);
        QWidget::setTabOrder(lineEditParcelAreaMin, lineEditParcelAreaMax);
        QWidget::setTabOrder(lineEditParcelAreaMax, lineEditParcelAreaDev);
        QWidget::setTabOrder(lineEditParcelAreaDev, lineEditSetbackFrontMin);
        QWidget::setTabOrder(lineEditSetbackFrontMin, lineEditSetbackFrontMax);
        QWidget::setTabOrder(lineEditSetbackFrontMax, lineEditSetbackRearMin);
        QWidget::setTabOrder(lineEditSetbackRearMin, lineEditSetbackRearMax);
        QWidget::setTabOrder(lineEditSetbackRearMax, lineEditSetbackSideMin);
        QWidget::setTabOrder(lineEditSetbackSideMin, lineEditSetbackSideMax);
        QWidget::setTabOrder(lineEditSetbackSideMax, lineEditNumStoriesMin);
        QWidget::setTabOrder(lineEditNumStoriesMin, lineEditNumStoriesMax);
        QWidget::setTabOrder(lineEditNumStoriesMax, lineEditMinBuildingDimMin);
        QWidget::setTabOrder(lineEditMinBuildingDimMin, lineEditMinBuildingDimMax);
        QWidget::setTabOrder(lineEditMinBuildingDimMax, pushButtonOK);
        QWidget::setTabOrder(pushButtonOK, pushButtonCancel);

        retranslateUi(ScenarioGenerationDialog);

        QMetaObject::connectSlotsByName(ScenarioGenerationDialog);
    } // setupUi

    void retranslateUi(QDialog *ScenarioGenerationDialog)
    {
        ScenarioGenerationDialog->setWindowTitle(QApplication::translate("ScenarioGenerationDialog", "Scenario Generation Dialog", Q_NULLPTR));
        pushButtonOK->setText(QApplication::translate("ScenarioGenerationDialog", "OK", Q_NULLPTR));
        pushButtonCancel->setText(QApplication::translate("ScenarioGenerationDialog", "Cancel", Q_NULLPTR));
        label->setText(QApplication::translate("ScenarioGenerationDialog", "# Scenarios:", Q_NULLPTR));
        label_2->setText(QApplication::translate("ScenarioGenerationDialog", "Output directory:", Q_NULLPTR));
        pushButtonOutputDirectory->setText(QApplication::translate("ScenarioGenerationDialog", "...", Q_NULLPTR));
        label_13->setText(QApplication::translate("ScenarioGenerationDialog", "Zone:", Q_NULLPTR));
        label_14->setText(QApplication::translate("ScenarioGenerationDialog", "Terrain:", Q_NULLPTR));
        pushButtonZone->setText(QApplication::translate("ScenarioGenerationDialog", "...", Q_NULLPTR));
        pushButtonTerrain->setText(QApplication::translate("ScenarioGenerationDialog", "...", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("ScenarioGenerationDialog", "Roads", Q_NULLPTR));
        label_9->setText(QApplication::translate("ScenarioGenerationDialog", "Road curvature:", Q_NULLPTR));
        label_6->setText(QApplication::translate("ScenarioGenerationDialog", "Road base orientation:", Q_NULLPTR));
        label_3->setText(QApplication::translate("ScenarioGenerationDialog", "Avenue segment length:", Q_NULLPTR));
        label_4->setText(QApplication::translate("ScenarioGenerationDialog", "~", Q_NULLPTR));
        label_7->setText(QApplication::translate("ScenarioGenerationDialog", "~", Q_NULLPTR));
        label_10->setText(QApplication::translate("ScenarioGenerationDialog", "~", Q_NULLPTR));
        label_5->setText(QApplication::translate("ScenarioGenerationDialog", "[m]", Q_NULLPTR));
        label_8->setText(QApplication::translate("ScenarioGenerationDialog", "[deg]", Q_NULLPTR));
        label_29->setText(QApplication::translate("ScenarioGenerationDialog", "Major road width:", Q_NULLPTR));
        label_30->setText(QApplication::translate("ScenarioGenerationDialog", "[m]", Q_NULLPTR));
        label_31->setText(QApplication::translate("ScenarioGenerationDialog", "~", Q_NULLPTR));
        label_32->setText(QApplication::translate("ScenarioGenerationDialog", "Minor road width:", Q_NULLPTR));
        label_35->setText(QApplication::translate("ScenarioGenerationDialog", "[m]", Q_NULLPTR));
        label_39->setText(QApplication::translate("ScenarioGenerationDialog", "~", Q_NULLPTR));
        label_42->setText(QApplication::translate("ScenarioGenerationDialog", "Use elevation:", Q_NULLPTR));
        checkBoxUseElevation->setText(QString());
        groupBox_2->setTitle(QApplication::translate("ScenarioGenerationDialog", "Parcels", Q_NULLPTR));
        label_11->setText(QApplication::translate("ScenarioGenerationDialog", "Park ratio:", Q_NULLPTR));
        label_12->setText(QApplication::translate("ScenarioGenerationDialog", "~", Q_NULLPTR));
        label_15->setText(QApplication::translate("ScenarioGenerationDialog", "Parcel area:", Q_NULLPTR));
        label_16->setText(QApplication::translate("ScenarioGenerationDialog", "~", Q_NULLPTR));
        label_17->setText(QApplication::translate("ScenarioGenerationDialog", "Setback front:", Q_NULLPTR));
        label_18->setText(QApplication::translate("ScenarioGenerationDialog", "~", Q_NULLPTR));
        label_19->setText(QApplication::translate("ScenarioGenerationDialog", "Setback rear:", Q_NULLPTR));
        label_20->setText(QApplication::translate("ScenarioGenerationDialog", "~", Q_NULLPTR));
        label_21->setText(QApplication::translate("ScenarioGenerationDialog", "Setback side:", Q_NULLPTR));
        label_22->setText(QApplication::translate("ScenarioGenerationDialog", "~", Q_NULLPTR));
        label_38->setText(QApplication::translate("ScenarioGenerationDialog", "Std Dev:", Q_NULLPTR));
        label_23->setText(QApplication::translate("ScenarioGenerationDialog", "[m]", Q_NULLPTR));
        label_24->setText(QApplication::translate("ScenarioGenerationDialog", "[m]", Q_NULLPTR));
        label_25->setText(QApplication::translate("ScenarioGenerationDialog", "[m]", Q_NULLPTR));
        label_26->setText(QApplication::translate("ScenarioGenerationDialog", "[m^2]", Q_NULLPTR));
        groupBox_3->setTitle(QApplication::translate("ScenarioGenerationDialog", "Buildings", Q_NULLPTR));
        label_33->setText(QApplication::translate("ScenarioGenerationDialog", "# Stories:", Q_NULLPTR));
        label_34->setText(QApplication::translate("ScenarioGenerationDialog", "~", Q_NULLPTR));
        label_36->setText(QApplication::translate("ScenarioGenerationDialog", "Min dimension:", Q_NULLPTR));
        label_37->setText(QApplication::translate("ScenarioGenerationDialog", "~", Q_NULLPTR));
        label_27->setText(QApplication::translate("ScenarioGenerationDialog", "[m]", Q_NULLPTR));
        label_43->setText(QApplication::translate("ScenarioGenerationDialog", "Building coverage:", Q_NULLPTR));
        checkBoxBuildingCoverage->setText(QString());
        label_44->setText(QApplication::translate("ScenarioGenerationDialog", "~", Q_NULLPTR));
        label_45->setText(QApplication::translate("ScenarioGenerationDialog", "[%]", Q_NULLPTR));
        label_28->setText(QApplication::translate("ScenarioGenerationDialog", "Simulator directory:", Q_NULLPTR));
        pushButtonSimulatorDirectory->setText(QApplication::translate("ScenarioGenerationDialog", "...", Q_NULLPTR));
        checkBoxUseSimulator->setText(QApplication::translate("ScenarioGenerationDialog", "Use simulator", Q_NULLPTR));
        label_40->setText(QApplication::translate("ScenarioGenerationDialog", "Generate building footprints image?", Q_NULLPTR));
        checkBoxGenerateBuildingFootprintsImage->setText(QApplication::translate("ScenarioGenerationDialog", "Yes", Q_NULLPTR));
        label_41->setText(QApplication::translate("ScenarioGenerationDialog", "Image size:", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class ScenarioGenerationDialog: public Ui_ScenarioGenerationDialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SCENARIOGENERATIONDIALOG_H
